# -*- coding: utf-8 -*-
"""stroke_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ANWJxMStVoFjXT74B_xKu0NfuqXp7A98
"""

import zipfile
from google.colab import drive

drive.mount('/content/drive/')

zip_ref = zipfile.ZipFile('/content/stroke.zip', 'r')
zip_ref.extractall()
zip_ref.close()

import pandas as pd



import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/healthcare-dataset-stroke-data.csv')

df

df.drop(labels=['id','ever_married',	'work_type','bmi',	'Residence_type'], axis=1,inplace=True)

df.dropna(inplace = True)







df

from sklearn.preprocessing import LabelEncoder

le =  LabelEncoder()
for i in df:
    if df[i].dtype=='object':
        df[i] = le.fit_transform(df[i])
    else:
        continue

X = df.drop(['stroke'],axis=1)
y = df['stroke']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import f1_score

model = RandomForestClassifier()

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print(y_pred[:15])



from sklearn.metrics import  recall_score, accuracy_score, classification_report





accuracy = accuracy_score(y_pred, y_test)





print(accuracy)

print(classification_report(y_test,y_pred))
print('F1 Score: ',f1_score(y_test,y_pred,zero_division=1))

from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)

print(confmat)

fig, ax =plt.subplots(figsize=(12.5, 12.5))
ax.matshow(confmat,  cmap=plt.cm.Blues, alpha=0.30)
for i in range(confmat.shape[0]):
  for j in range(confmat.shape[1]):
    ax.text(x=j, y=i,
            s=confmat[i, j],
            va='center', ha='center')
    plt.title('Using the RandForestClassifier model at 94% accuracy prediction on the stroke dataset for identifying false negatives and false positives as well as true positives and true negatives. With 0 did not have a stroke and 1 had a stroke.')
    plt.xlabel('Predicted label')
    plt.ylabel('True Label')